### PR TITLE
Fix macos pluginval crash

### LINKED ISSUE #46: pluginval crash
pluginval with strictness 10 on macOS causes the plugin to crash.

### PR DESCRIPTION
**Pull request by yetyetanotherusername**
Closes #46

### CODE REVIEW

File: source/PluginProcessor.cpp [hunk 1]
```diff
@@ -2426,10 +2403,6 @@ void PolarDesignerAudioProcessor::setProxCompCoefficients (float distance)
 
 void PolarDesignerAudioProcessor::timerCallback()
 {
-    validateSampleRateAndBlockSize(); // Validate before operations
-
-    recomputeFilterCoefficientsIfNeeded();
```
Comment (yetyetanotherusername) [inline source/PluginProcessor.cpp]: This is the culprit of the crash.

`timerCallback()` triggers recomputeFilterCoefficients regardless of whether the plugin is prepared or not.

This is not good. We should recompute filter coefficients when parameters change, not based on a timer.

**Review by DanielRudrich — APPROVED** [review]
